name: unibo-cdmo
channels:
  - mosek
  - conda-forge
  - defaults
dependencies:
  - conda
  - pandas
  - pip
  - python=3.8
  - numpy
  - matplotlib
  - pip:
    - black
    - minizinc[dzn]
    - z3-solver
    - pulp