name: vlsi-design
channels:
  - mosek
  - conda-forge
  - defaults
dependencies:
  - black
  - numpy
  - pip
  - matplotlib
  - python=3.8
  - pandas
  - mosek
  - pip:
    - pysmt==0.9.5
    - minizinc[dzn]==0.7.0
    - pulp==2.6.0